name: Build and deploy Vue3 App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install

      - name: .env setup
        run: echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ vars.LIVE_ENV_FILE }}

      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIVE_HOST }}
          username: ${{ secrets.LIVE_USERNAME }}
          password: ${{ secrets.LIVE_PASSWORD }}
          port: ${{ secrets.LIVE_PORT }}
          source: "dist/*"
          target: "/home/deploy/taskfocus_web/dist/"
          strip_components: 1
