name: Build and deploy Vue3 App

on:
  push:
    branches:
      - stage
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: copy over ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_USERNAME }}
          password: ${{ secrets.STAGE_PASSWORD }}
          port: ${{ secrets.STAGE_PORT }}
          source: "index.html"
          target: "/home/deploy/web/www"