name: Build and deploy Vue3 App

on:
  push:
    branches:
      - stage
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - uses: actions/checkout@master
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_USERNAME }}
          password: ${{ secrets.STAGE_PASSWORD }}
          port: ${{ secrets.STAGE_PORT }}
          source: "dist/*"
          target: "/home/deploy/www/web"