name: Build and deploy Vue3 App to Stage

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Checkout repo
        uses: actions/checkout@master

      - name: Install dependencies
        run: npm install

      - name: .env setup
        run: echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ vars.ENV_FILE }}

      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_USERNAME }}
          key: ${{ secrets.STAGE_KEY }}
          port: ${{ secrets.STAGE_PORT }}
          source: "dist/*"
          target: "/home/deploy/www/web/"
          strip_components: 1